# Generated by Django 5.0.4 on 2025-03-02 20:43

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CantidadMemoria',
            fields=[
                ('id_cantidad_memoria', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(unique=True, verbose_name='Cantidad (GB)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id_caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoDispositivo',
            fields=[
                ('id_estado_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id_tipo_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMemoria',
            fields=[
                ('id_tipo_memoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('nomenclatura', models.CharField(max_length=45, unique=True, verbose_name='Nomenclatura')),
                ('serie', models.CharField(blank=True, max_length=45, null=True, verbose_name='Número de Serie')),
                ('jira', models.CharField(blank=True, max_length=45, null=True, verbose_name='Jira Ticket')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.tipodispositivo', verbose_name='Tipo de Dispositivo')),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoPropietarioHistorico',
            fields=[
                ('id_dispositivo_propietario_historico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(verbose_name='Fecha de Cambio')),
                ('comentario', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_propietario_historico', to=settings.AUTH_USER_MODEL, verbose_name='Agente del Cambio de Propietario')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo')),
                ('propietario_id_anterior', models.ForeignKey(blank=True, db_column='propietario_id_anterior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_anterior', to=settings.AUTH_USER_MODEL, verbose_name='Propietario Anterior')),
                ('propietario_id_nuevo', models.ForeignKey(blank=True, db_column='propietario_id_nuevo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_nuevo', to=settings.AUTH_USER_MODEL, verbose_name='Propietario Nuevo')),
            ],
            options={
                'verbose_name': 'Dispositivo Propietario Histórico',
                'verbose_name_plural': 'Dispositivos Propietarios Históricos',
            },
        ),
        migrations.CreateModel(
            name='DispositivoEstado',
            fields=[
                ('id_dispositivo_estado', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comentario', models.CharField(blank=True, max_length=45, null=True, verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_dispositivo', to=settings.AUTH_USER_MODEL, verbose_name='Agente del Cambio de Estado')),
                ('dispositivo_id_dispositivo', models.ForeignKey(db_column='dispositivo_id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo')),
                ('estado_id_estado', models.ForeignKey(db_column='estado_id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.estadodispositivo', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Dispositivo Estado',
                'verbose_name_plural': 'Dispositivos Estados',
            },
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id_gerencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventario.gerencia', verbose_name='Gerencia Superior')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=45, verbose_name='Agencia')),
                ('piso', models.CharField(blank=True, max_length=45, null=True, verbose_name='Piso')),
                ('zona', models.CharField(choices=[('Norte', 'Zona Norte'), ('Centro', 'Zona Centro')], default='Norte', max_length=10, verbose_name='Zona')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'unique_together': {('agencia', 'piso', 'zona')},
            },
        ),
        migrations.CreateModel(
            name='DispositivoUbicacion',
            fields=[
                ('id_dispositivo_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comentario', models.CharField(blank=True, max_length=45, null=True, verbose_name='Comentario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_ubicacion_dispositivo', to=settings.AUTH_USER_MODEL, verbose_name='Agente del Cambio de Ubicación')),
                ('dispositivo_id_dispositivo', models.ForeignKey(db_column='dispositivo_id_dispositivo', on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo')),
                ('ubicacion_id_ubicacion', models.ForeignKey(db_column='ubicacion_id_ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Dispositivo Ubicación',
                'verbose_name_plural': 'Dispositivos Ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='DispositivoCaracteristica',
            fields=[
                ('id_dispositivo_caracteristica', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=45, verbose_name='Valor')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.caracteristica', verbose_name='Característica')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.dispositivo', verbose_name='Dispositivo')),
            ],
            options={
                'unique_together': {('dispositivo', 'caracteristica')},
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('marca_id_marca', models.ForeignKey(db_column='marca_id_marca', on_delete=django.db.models.deletion.DO_NOTHING, to='inventario.marca', verbose_name='Marca')),
            ],
            options={
                'unique_together': {('nombre', 'marca_id_marca')},
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaTipoDispositivo',
            fields=[
                ('id_caracteristica_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('obligatorio', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.caracteristica', verbose_name='Característica')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipodispositivo', verbose_name='Tipo de Dispositivo')),
            ],
            options={
                'unique_together': {('caracteristica', 'tipo_dispositivo')},
            },
        ),
    ]
